# Goal : build the image  for DEVBOARD  Frontend and push  it to docker Hub 
name: CI

on:
    push:
      branches: [master]
      

jobs:
     build-and-push:
       runs-on: ubuntu-latest
       steps:
# Downloading the code form  repository to virtual server created by github action
         - name: Downloading the code 
           uses: actions/checkout@v7
# here we try to login in docker hub  account 
         - name: login in to docker hub 
           uses: docker/login-action@v4
           with: 
             username: ${{ vars.DOCKERHUB_USERNAME }}
             password: ${{ secrets.DOCKERHUB_TOKEN }}
# here we try to  push the builded image to own docker  hub acoount
         - name: Build and push
           uses: docker/build-push-action@v7
           with:
             push: true
             tags: ${{ vars.DOCKERHUB_USERNAME }}/devboarda-fe-master:test

             
             

       
         
    

     
