# Goal to install the multiple version of the GO language and to  cheking the linting 

name: go linter

on:
    schedule:
        - cron: '58 10 * * *' 

jobs:
    code_build:
        
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                go-version: [1.22.0, 1.22.1, 1.23.0]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup GO 
              uses: actions/setup-go@v6
              with:
                    go-version: ${{ matrix.go-version }}
                    go-version-file: go.mod
                    cache-dependency-path: |
                        **/go.sum
                        **/go.mod
            - name: Run Go Formater
              #run: go fmt ./...
              env:
                GOTOOLCHAIN: auto
              run: go fmt ./...

              working-directory:  backend
            - name: Run go vet
              #run: go vet ./...
              env:
                GOTOOLCHAIN: auto
              run: go vet  

              working-directory:  backend  